version: '2'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "test:4:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    influx:
        image: influxdb
        ports:
          - "8086:8086"
        volumes:
          - influxdb-storage:/var/lib/influxdb
        environment:
          - INFLUXDB_DB=flink
    grafana:
        image: grafana/grafana
        ports:
         - "3000:3000"
        volumes:
         - grafana-storage:/var/lib/grafana

volumes:
    grafana-storage:
    influxdb-storage:
